//! PKCS#12 and PEM keystore loading.
//!
//! Supports both legacy PKCS#12 (3DES/RC2, via the `p12` crate) and modern
//! PKCS#12 (PBES2+PBKDF2+AES-256-CBC, as generated by DevEco Studio), via
//! the `pkcs12` + `pkcs5` + `pkcs8` RustCrypto crates.

use std::path::Path;
use std::time::SystemTime;

use crate::error::SignError;
use der::{Decode, Encode};
use x509_cert::Certificate;
use zeroize::Zeroize;

/// A loaded signing key + certificate chain.
pub struct SigningKey {
    /// PKCS#8 DER-encoded private key.
    pub private_key_der: Vec<u8>,
    /// DER-encoded X.509 certificates, leaf first.
    pub cert_chain: Vec<Vec<u8>>,
}

impl Drop for SigningKey {
    fn drop(&mut self) {
        self.private_key_der.zeroize();
    }
}

impl SigningKey {
    pub(crate) fn normalize_certificate_chain(
        mut certificates: Vec<Vec<u8>>,
    ) -> Result<Vec<Vec<u8>>, SignError> {
        if certificates.is_empty() {
            return Err(SignError::NoCertificate);
        }
        for certificate in &certificates {
            Self::validate_certificate_der(certificate)?;
        }
        Self::sort_certificate_chain(&mut certificates)?;
        Self::verify_certificate_chain(&certificates)?;
        Ok(certificates)
    }

    pub(crate) fn normalize_profile_certificate_chain_at(
        mut certificates: Vec<Vec<u8>>,
        signing_time: SystemTime,
    ) -> Result<Vec<Vec<u8>>, SignError> {
        if certificates.is_empty() {
            return Err(SignError::NoCertificate);
        }
        for certificate in &certificates {
            Self::validate_certificate_der(certificate)?;
        }
        Self::sort_certificate_chain(&mut certificates)?;
        Self::verify_certificate_chain_at(&certificates, signing_time, true)?;
        Ok(certificates)
    }

    /// Load either a Java JKS (`0xFEEDFEED`) or PKCS#12 keystore using the
    /// same format auto-detection performed by official `KeyStoreHelper`.
    pub fn from_keystore(
        bytes: &[u8],
        store_password: &str,
        key_alias: &str,
        key_password: &str,
    ) -> Result<Self, SignError> {
        const JKS_MAGIC: [u8; 4] = 0xFEED_FEEDu32.to_be_bytes();
        if bytes.starts_with(&JKS_MAGIC) {
            Self::from_jks(bytes, store_password, key_alias, key_password)
        } else {
            Self::from_pkcs12(bytes, store_password, key_alias, key_password)
        }
    }

    /// Load a legacy Java KeyStore and decrypt the selected private-key entry.
    pub fn from_jks(
        jks_bytes: &[u8],
        store_password: &str,
        key_alias: &str,
        key_password: &str,
    ) -> Result<Self, SignError> {
        let mut store = jks::KeyStore::new();
        store
            .load(jks_bytes, store_password.as_bytes())
            .map_err(|error| SignError::KeystoreParseError(format!("JKS parse: {error}")))?;
        let available = store.aliases();
        if !store.is_private_key_entry(key_alias) {
            return Err(SignError::KeyAliasNotFound {
                alias: key_alias.to_owned(),
                available,
            });
        }
        let entry = store
            .get_private_key_entry(key_alias, key_password.as_bytes())
            .map_err(|error| {
                SignError::KeystoreParseError(format!(
                    "JKS private key '{key_alias}' decrypt: {error}"
                ))
            })?;
        if entry.private_key.is_empty() {
            return Err(SignError::NoPrivateKey);
        }
        let cert_chain = entry
            .certificate_chain
            .into_iter()
            .map(|certificate| certificate.content)
            .collect::<Vec<_>>();
        if cert_chain.is_empty() {
            return Err(SignError::NoCertificate);
        }
        Ok(Self {
            private_key_der: entry.private_key,
            cert_chain,
        })
    }

    /// Load from a PKCS#12 (.p12 / .pfx) file.
    ///
    /// Tries the modern PBES2/AES-256-CBC path first (DevEco Studio keys),
    /// then falls back to the legacy 3DES/RC2 path.
    ///
    pub fn from_pkcs12(
        p12_bytes: &[u8],
        store_password: &str,
        key_alias: &str,
        key_password: &str,
    ) -> Result<Self, SignError> {
        // Try modern PBES2 path first (DevEco Studio / OpenSSL 3.x default).
        match Self::from_pkcs12_pbes2(p12_bytes, store_password, key_alias, key_password) {
            Ok(k) => Ok(k),
            Err(error @ SignError::KeyAliasNotFound { .. }) => Err(error),
            Err(e_modern) => {
                // Fall back to legacy p12 crate (3DES / RC2).
                match Self::from_pkcs12_legacy(p12_bytes, store_password, key_alias, key_password) {
                    Ok(key) => Ok(key),
                    Err(error @ SignError::KeyAliasNotFound { .. }) => Err(error),
                    Err(e_legacy) => Err(SignError::KeystoreParseError(format!(
                        "PKCS#12 parse failed (modern: {e_modern}; legacy: {e_legacy})"
                    ))),
                }
            }
        }
    }

    /// Load the application certificate chain from hapsigner `appCertFile`.
    ///
    /// Java hapsigner reads this with
    /// `CertificateFactory.getInstance("X.509").generateCertificates(...)`,
    /// sorts the chain to leaf-first order, then validates the chain relation.
    pub fn cert_chain_from_file(path: &Path) -> Result<Vec<Vec<u8>>, SignError> {
        let bytes = fs_err::read(path)?;
        Self::cert_chain_from_bytes(&bytes)
    }

    /// Load, normalize, and validate a PEM or concatenated DER certificate
    /// chain supplied by the caller. The returned chain is leaf-first, matching
    /// `hap-sign-tool -appCertFile` behavior.
    pub fn cert_chain_from_bytes(bytes: &[u8]) -> Result<Vec<Vec<u8>>, SignError> {
        let mut certs = if Self::is_pem_certificate_file(bytes) {
            Self::cert_chain_from_pem_bytes(bytes)?
        } else {
            Self::cert_chain_from_der_bytes(bytes)?
        };
        if certs.is_empty() {
            return Err(SignError::NoCertificate);
        }
        Self::sort_certificate_chain(&mut certs)?;
        Self::verify_certificate_chain(&certs)?;
        Ok(certs)
    }

    fn is_pem_certificate_file(bytes: &[u8]) -> bool {
        bytes
            .windows(b"-----BEGIN CERTIFICATE-----".len())
            .any(|window| window == b"-----BEGIN CERTIFICATE-----")
    }

    fn cert_chain_from_pem_bytes(bytes: &[u8]) -> Result<Vec<Vec<u8>>, SignError> {
        const BEGIN: &str = "-----BEGIN CERTIFICATE-----";
        const END: &str = "-----END CERTIFICATE-----";

        let text = std::str::from_utf8(bytes)
            .map_err(|e| SignError::PemError(format!("certificate file is not UTF-8 PEM: {e}")))?;
        let mut rest = text;
        let mut certs = Vec::new();

        while let Some(begin_index) = rest.find(BEGIN) {
            let after_begin = &rest[begin_index + BEGIN.len()..];
            let end_index = after_begin.find(END).ok_or_else(|| {
                SignError::PemError("certificate PEM block missing END marker".to_string())
            })?;
            let body = &after_begin[..end_index];
            let encoded = body.lines().map(str::trim).collect::<String>();
            let cert_der =
                base64_decode(&encoded).map_err(|e| SignError::PemError(e.to_string()))?;
            Self::validate_certificate_der(&cert_der)?;
            certs.push(cert_der);
            rest = &after_begin[end_index + END.len()..];
        }

        Ok(certs)
    }

    fn cert_chain_from_der_bytes(bytes: &[u8]) -> Result<Vec<Vec<u8>>, SignError> {
        let mut certs = Vec::new();
        let mut remaining = bytes;
        while !remaining.is_empty() {
            let cert_len = Self::der_tlv_len(remaining)?;
            let cert_der = remaining[..cert_len].to_vec();
            Self::validate_certificate_der(&cert_der)?;
            certs.push(cert_der);
            remaining = &remaining[cert_len..];
        }
        Ok(certs)
    }

    fn der_tlv_len(bytes: &[u8]) -> Result<usize, SignError> {
        if bytes.len() < 2 || bytes[0] != 0x30 {
            return Err(SignError::DerError(
                "certificate DER must start with SEQUENCE".to_string(),
            ));
        }
        let length_byte = bytes[1];
        let (length_len, content_len) = if length_byte & 0x80 == 0 {
            (0usize, length_byte as usize)
        } else {
            let length_len = (length_byte & 0x7f) as usize;
            if length_len == 0 || length_len > 4 || bytes.len() < 2 + length_len {
                return Err(SignError::DerError(
                    "certificate DER has invalid length field".to_string(),
                ));
            }
            let mut content_len = 0usize;
            for byte in &bytes[2..2 + length_len] {
                content_len = (content_len << 8) | (*byte as usize);
            }
            (length_len, content_len)
        };
        let total_len = 2 + length_len + content_len;
        if total_len > bytes.len() {
            return Err(SignError::DerError(
                "certificate DER length exceeds input".to_string(),
            ));
        }
        Ok(total_len)
    }

    fn validate_certificate_der(cert_der: &[u8]) -> Result<(), SignError> {
        Certificate::from_der(cert_der)
            .map(|_| ())
            .map_err(|e| SignError::DerError(format!("certificate parse: {e}")))
    }

    fn sort_certificate_chain(certs: &mut [Vec<u8>]) -> Result<(), SignError> {
        if certs.len() <= 1 {
            return Ok(());
        }
        let subjects = certs
            .iter()
            .map(|certificate| Self::certificate_subject_der(certificate))
            .collect::<Result<Vec<_>, _>>()?;
        let issuers = certs
            .iter()
            .map(|certificate| Self::certificate_issuer_der(certificate))
            .collect::<Result<Vec<_>, _>>()?;
        let leaf_candidates = (0..certs.len())
            .filter(|candidate| {
                !(0..certs.len())
                    .any(|other| other != *candidate && issuers[other] == subjects[*candidate])
            })
            .collect::<Vec<_>>();
        let [leaf] = leaf_candidates.as_slice() else {
            return Err(SignError::DerError(
                "certificate set does not contain one unambiguous leaf".to_owned(),
            ));
        };
        let mut order = Vec::with_capacity(certs.len());
        order.push(*leaf);
        while order.len() < certs.len() {
            let current = *order.last().expect("certificate order has a leaf");
            let parent = (0..certs.len()).find(|candidate| {
                !order.contains(candidate) && subjects[*candidate] == issuers[current]
            });
            let Some(parent) = parent else {
                return Err(SignError::DerError(
                    "certificate set is disconnected".to_owned(),
                ));
            };
            order.push(parent);
        }
        let sorted = order
            .into_iter()
            .map(|index| certs[index].clone())
            .collect::<Vec<_>>();
        for (target, certificate) in certs.iter_mut().zip(sorted) {
            *target = certificate;
        }
        Ok(())
    }

    fn verify_certificate_chain(certs: &[Vec<u8>]) -> Result<(), SignError> {
        Self::verify_certificate_chain_at(certs, SystemTime::now(), false)
    }

    fn verify_certificate_chain_at(
        certs: &[Vec<u8>],
        validation_time: SystemTime,
        validate_single: bool,
    ) -> Result<(), SignError> {
        if certs.len() <= 1 {
            if validate_single {
                let certificate = certs.first().ok_or(SignError::NoCertificate)?;
                let certificate = Certificate::from_der(certificate)
                    .map_err(|e| SignError::DerError(format!("certificate parse: {e}")))?;
                Self::check_certificate_validity_at(&certificate, validation_time)?;
            }
            return Ok(());
        }

        let parsed = certs
            .iter()
            .map(|cert_der| {
                Certificate::from_der(cert_der)
                    .map_err(|e| SignError::DerError(format!("certificate parse: {e}")))
            })
            .collect::<Result<Vec<_>, _>>()?;

        for i in 1..parsed.len() {
            let child = &parsed[i - 1];
            let parent = &parsed[i];
            Self::verify_certificate_signature(child, parent)?;
            Self::check_certificate_validity_at(child, validation_time)?;

            let child_issuer = child
                .tbs_certificate
                .issuer
                .to_der()
                .map_err(|e| SignError::DerError(format!("issuer encode: {e}")))?;
            let parent_subject = parent
                .tbs_certificate
                .subject
                .to_der()
                .map_err(|e| SignError::DerError(format!("subject encode: {e}")))?;
            if child_issuer != parent_subject {
                return Err(SignError::DerError(
                    "certificate chain issuer does not match parent subject".to_string(),
                ));
            }

            if i == parsed.len() - 1 {
                Self::check_certificate_validity_at(parent, validation_time)?;
            }
        }
        Ok(())
    }

    fn check_certificate_validity_at(
        cert: &Certificate,
        validation_time: SystemTime,
    ) -> Result<(), SignError> {
        let validity = &cert.tbs_certificate.validity;
        let not_before = validity.not_before.to_system_time();
        let not_after = validity.not_after.to_system_time();
        if validation_time < not_before {
            return Err(SignError::DerError(
                "certificate chain contains a certificate that is not yet valid".to_string(),
            ));
        }
        if validation_time > not_after {
            return Err(SignError::DerError(
                "certificate chain contains an expired certificate".to_string(),
            ));
        }
        Ok(())
    }

    fn verify_certificate_signature(
        child: &Certificate,
        parent: &Certificate,
    ) -> Result<(), SignError> {
        let tbs_der = child
            .tbs_certificate
            .to_der()
            .map_err(|e| SignError::DerError(format!("TBS certificate encode: {e}")))?;
        let signature = child.signature.as_bytes().ok_or_else(|| {
            SignError::DerError("certificate signature has unused bits".to_string())
        })?;
        let signature_oid = child.signature_algorithm.oid.to_string();
        match signature_oid.as_str() {
            "1.2.840.10045.4.3.2" => {
                Self::verify_ecdsa_certificate_signature(parent, &tbs_der, signature, "SHA256")
            }
            "1.2.840.10045.4.3.3" => {
                Self::verify_ecdsa_certificate_signature(parent, &tbs_der, signature, "SHA384")
            }
            "1.2.840.10045.4.3.4" => {
                Self::verify_ecdsa_certificate_signature(parent, &tbs_der, signature, "SHA512")
            }
            "1.2.840.113549.1.1.11" => {
                Self::verify_rsa_pkcs1_sha256_certificate_signature(parent, &tbs_der, signature)
            }
            "1.2.840.113549.1.1.12" => {
                Self::verify_rsa_pkcs1_sha384_certificate_signature(parent, &tbs_der, signature)
            }
            "1.2.840.113549.1.1.13" => {
                Self::verify_rsa_pkcs1_sha512_certificate_signature(parent, &tbs_der, signature)
            }
            other => Err(SignError::DerError(format!(
                "unsupported certificate signature algorithm: {other}"
            ))),
        }
    }

    fn verify_ecdsa_certificate_signature(
        parent: &Certificate,
        tbs_der: &[u8],
        signature: &[u8],
        digest: &str,
    ) -> Result<(), SignError> {
        let public_key = parent
            .tbs_certificate
            .subject_public_key_info
            .subject_public_key
            .as_bytes()
            .ok_or_else(|| {
                SignError::DerError("parent EC public key has unused bits".to_string())
            })?;
        use sha2::Digest;
        use signature::hazmat::PrehashVerifier;

        let prehash = match digest {
            "SHA256" => sha2::Sha256::digest(tbs_der).to_vec(),
            "SHA384" => sha2::Sha384::digest(tbs_der).to_vec(),
            "SHA512" => sha2::Sha512::digest(tbs_der).to_vec(),
            digest => {
                return Err(SignError::DerError(format!(
                    "unsupported ECDSA certificate digest: {digest}"
                )))
            }
        };
        match public_key.len() {
            65 => {
                let verifier = p256::ecdsa::VerifyingKey::from_sec1_bytes(public_key)
                    .map_err(|error| SignError::DerError(format!("parent P-256 key: {error}")))?;
                let signature = p256::ecdsa::DerSignature::from_bytes(signature)
                    .map_err(|error| SignError::DerError(format!("P-256 signature: {error}")))?;
                verifier.verify_prehash(&prehash, &signature).map_err(|_| {
                    SignError::DerError("verify certificate chain signature failed".to_string())
                })
            }
            97 => {
                let verifier = p384::ecdsa::VerifyingKey::from_sec1_bytes(public_key)
                    .map_err(|error| SignError::DerError(format!("parent P-384 key: {error}")))?;
                let signature = p384::ecdsa::DerSignature::from_bytes(signature)
                    .map_err(|error| SignError::DerError(format!("P-384 signature: {error}")))?;
                verifier.verify_prehash(&prehash, &signature).map_err(|_| {
                    SignError::DerError("verify certificate chain signature failed".to_string())
                })
            }
            len => Err(SignError::DerError(format!(
                "unsupported ECDSA certificate verification key length: {len}"
            ))),
        }
    }

    fn verify_rsa_pkcs1_sha256_certificate_signature(
        parent: &Certificate,
        tbs_der: &[u8],
        signature: &[u8],
    ) -> Result<(), SignError> {
        use rsa::pkcs8::DecodePublicKey;
        use signature::Verifier;

        let spki_der = parent
            .tbs_certificate
            .subject_public_key_info
            .to_der()
            .map_err(|e| SignError::DerError(format!("parent RSA SPKI encode: {e}")))?;
        let public_key = rsa::RsaPublicKey::from_public_key_der(&spki_der)
            .map_err(|e| SignError::DerError(format!("parent RSA public key parse: {e}")))?;
        let signature = rsa::pkcs1v15::Signature::try_from(signature)
            .map_err(|e| SignError::DerError(format!("RSA PKCS1 signature parse: {e}")))?;
        let verifier = rsa::pkcs1v15::VerifyingKey::<sha2::Sha256>::new(public_key);
        verifier.verify(tbs_der, &signature).map_err(|e| {
            SignError::DerError(format!("verify certificate chain signature failed: {e}"))
        })
    }

    fn verify_rsa_pkcs1_sha384_certificate_signature(
        parent: &Certificate,
        tbs_der: &[u8],
        signature: &[u8],
    ) -> Result<(), SignError> {
        use rsa::pkcs8::DecodePublicKey;
        use signature::Verifier;

        let spki_der = parent
            .tbs_certificate
            .subject_public_key_info
            .to_der()
            .map_err(|e| SignError::DerError(format!("parent RSA SPKI encode: {e}")))?;
        let public_key = rsa::RsaPublicKey::from_public_key_der(&spki_der)
            .map_err(|e| SignError::DerError(format!("parent RSA public key parse: {e}")))?;
        let signature = rsa::pkcs1v15::Signature::try_from(signature)
            .map_err(|e| SignError::DerError(format!("RSA PKCS1 signature parse: {e}")))?;
        let verifier = rsa::pkcs1v15::VerifyingKey::<sha2::Sha384>::new(public_key);
        verifier.verify(tbs_der, &signature).map_err(|e| {
            SignError::DerError(format!("verify certificate chain signature failed: {e}"))
        })
    }

    fn verify_rsa_pkcs1_sha512_certificate_signature(
        parent: &Certificate,
        tbs_der: &[u8],
        signature: &[u8],
    ) -> Result<(), SignError> {
        use rsa::pkcs8::DecodePublicKey;
        use signature::Verifier;

        let spki_der = parent
            .tbs_certificate
            .subject_public_key_info
            .to_der()
            .map_err(|e| SignError::DerError(format!("parent RSA SPKI encode: {e}")))?;
        let public_key = rsa::RsaPublicKey::from_public_key_der(&spki_der)
            .map_err(|e| SignError::DerError(format!("parent RSA public key parse: {e}")))?;
        let signature = rsa::pkcs1v15::Signature::try_from(signature)
            .map_err(|e| SignError::DerError(format!("RSA PKCS1 signature parse: {e}")))?;
        let verifier = rsa::pkcs1v15::VerifyingKey::<sha2::Sha512>::new(public_key);
        verifier.verify(tbs_der, &signature).map_err(|e| {
            SignError::DerError(format!("verify certificate chain signature failed: {e}"))
        })
    }

    fn certificate_issuer_der(cert_der: &[u8]) -> Result<Vec<u8>, SignError> {
        let cert = Certificate::from_der(cert_der)
            .map_err(|e| SignError::DerError(format!("certificate parse: {e}")))?;
        cert.tbs_certificate
            .issuer
            .to_der()
            .map_err(|e| SignError::DerError(format!("issuer encode: {e}")))
    }

    fn certificate_subject_der(cert_der: &[u8]) -> Result<Vec<u8>, SignError> {
        let cert = Certificate::from_der(cert_der)
            .map_err(|e| SignError::DerError(format!("certificate parse: {e}")))?;
        cert.tbs_certificate
            .subject
            .to_der()
            .map_err(|e| SignError::DerError(format!("subject encode: {e}")))
    }

    // -----------------------------------------------------------------------
    // Modern path: PBES2 + PBKDF2 + AES-256-CBC (DevEco Studio default)
    // -----------------------------------------------------------------------

    fn from_pkcs12_pbes2(
        p12_bytes: &[u8],
        store_password: &str,
        key_alias: &str,
        key_password: &str,
    ) -> Result<Self, SignError> {
        use cms::encrypted_data::EncryptedData;
        use const_oid::ObjectIdentifier;
        use der::asn1::{ContextSpecific, OctetString};
        use der::{Decode, Encode};
        use pkcs12::authenticated_safe::AuthenticatedSafe;
        use pkcs12::cert_type::CertBag;
        use pkcs12::pfx::Pfx;
        use pkcs12::safe_bag::SafeContents;

        // CMS content-type OIDs (RFC 5652).
        const ID_DATA: ObjectIdentifier = ObjectIdentifier::new_unwrap("1.2.840.113549.1.7.1");
        const ID_ENCRYPTED_DATA: ObjectIdentifier =
            ObjectIdentifier::new_unwrap("1.2.840.113549.1.7.6");

        // ── 1. Parse PFX ────────────────────────────────────────────────────
        let pfx = Pfx::from_der(p12_bytes)
            .map_err(|e| SignError::KeystoreParseError(format!("PFX DER parse: {e}")))?;

        // ── 2. Unwrap AuthenticatedSafe ──────────────────────────────────────
        // auth_safe.content is Any, which encodes as an OCTET STRING wrapping
        // the DER-encoded AuthenticatedSafe (SEQUENCE OF ContentInfo).
        let content_der = pfx
            .auth_safe
            .content
            .to_der()
            .map_err(|e| SignError::KeystoreParseError(format!("auth_safe to_der: {e}")))?;
        let auth_safe_os = OctetString::from_der(&content_der)
            .map_err(|e| SignError::KeystoreParseError(format!("auth_safe OctetString: {e}")))?;
        let auth_safes = AuthenticatedSafe::from_der(auth_safe_os.as_bytes())
            .map_err(|e| SignError::KeystoreParseError(format!("AuthenticatedSafe: {e}")))?;

        // ── 3. Walk ContentInfos ────────────────────────────────────────────
        let mut private_keys: Vec<(Option<String>, Vec<u8>)> = Vec::new();
        let mut cert_chain: Vec<Vec<u8>> = Vec::new();

        for content_info in &auth_safes {
            let safe_contents_bytes: Vec<u8>;

            if content_info.content_type == ID_DATA {
                // Plain safe bag — content is OCTET STRING(SafeContents)
                let os_der = content_info.content.to_der().map_err(|e| {
                    SignError::KeystoreParseError(format!("plain safe to_der: {e}"))
                })?;
                let os = OctetString::from_der(&os_der).map_err(|e| {
                    SignError::KeystoreParseError(format!("plain safe OctetString: {e}"))
                })?;
                safe_contents_bytes = os.as_bytes().to_vec();
            } else if content_info.content_type == ID_ENCRYPTED_DATA {
                // Encrypted safe bag — decrypt with PBES2 then parse SafeContents.
                let enc_der = content_info
                    .content
                    .to_der()
                    .map_err(|e| SignError::KeystoreParseError(format!("enc safe to_der: {e}")))?;
                let enc_data = EncryptedData::from_der(&enc_der).map_err(|e| {
                    SignError::KeystoreParseError(format!("EncryptedData parse: {e}"))
                })?;

                let params_der = enc_data
                    .enc_content_info
                    .content_enc_alg
                    .parameters
                    .as_ref()
                    .ok_or_else(|| {
                        SignError::KeystoreParseError("missing PBES2 parameters".into())
                    })?
                    .to_der()
                    .map_err(|e| {
                        SignError::KeystoreParseError(format!("PBES2 params to_der: {e}"))
                    })?;
                let algorithm_der =
                    enc_data
                        .enc_content_info
                        .content_enc_alg
                        .to_der()
                        .map_err(|error| {
                            SignError::KeystoreParseError(format!(
                                "encrypted-safe algorithm encode: {error}"
                            ))
                        })?;

                let enc_os = enc_data.enc_content_info.encrypted_content.ok_or_else(|| {
                    SignError::KeystoreParseError("missing encrypted content".into())
                })?;

                let original_ct = enc_os.as_bytes().to_vec();

                // Try store_password first; retry with key_password on failure.
                let decrypted = Self::decrypt_pkcs12_encryption(
                    &algorithm_der,
                    &params_der,
                    store_password,
                    &original_ct,
                )
                .or_else(|_| {
                    Self::decrypt_pkcs12_encryption(
                        &algorithm_der,
                        &params_der,
                        key_password,
                        &original_ct,
                    )
                })
                .map_err(|e| {
                    SignError::KeystoreParseError(format!("encrypted-safe decrypt: {e}"))
                })?;

                safe_contents_bytes = decrypted;
            } else {
                // Skip envelope types we don't handle.
                continue;
            }

            // ── 4. Parse SafeContents and collect key + certs ───────────────
            let safe_bags = SafeContents::from_der(&safe_contents_bytes)
                .map_err(|e| SignError::KeystoreParseError(format!("SafeContents parse: {e}")))?;

            for bag in safe_bags {
                match bag.bag_id {
                    pkcs12::PKCS_12_PKCS8_KEY_BAG_OID => {
                        // ShroudedKeyBag → [0] EXPLICIT EncryptedPrivateKeyInfo
                        let key = Self::decrypt_shrouded_key(&bag.bag_value, key_password)?;
                        private_keys.push((Self::modern_friendly_name(&bag)?, key));
                    }
                    pkcs12::PKCS_12_KEY_BAG_OID => {
                        // Plain (unencrypted) PKCS#8 KeyBag
                        use pkcs12::safe_bag::PrivateKeyInfo;
                        let cs: ContextSpecific<PrivateKeyInfo> =
                            ContextSpecific::from_der(&bag.bag_value).map_err(|e| {
                                SignError::KeystoreParseError(format!("key bag parse: {e}"))
                            })?;
                        let der = cs.value.to_der().map_err(|e| {
                            SignError::KeystoreParseError(format!("PrivateKeyInfo to_der: {e}"))
                        })?;
                        private_keys.push((Self::modern_friendly_name(&bag)?, der));
                    }
                    pkcs12::PKCS_12_CERT_BAG_OID => {
                        // CertBag → [0] EXPLICIT CertBag
                        let cs: ContextSpecific<CertBag> =
                            ContextSpecific::from_der(&bag.bag_value).map_err(|e| {
                                SignError::KeystoreParseError(format!("cert bag parse: {e}"))
                            })?;
                        cert_chain.push(cs.value.cert_value.as_bytes().to_vec());
                    }
                    _ => {} // skip unknown bag types
                }
            }
        }

        let private_key_der = Self::select_private_key(private_keys, key_alias)?;
        if cert_chain.is_empty() {
            return Err(SignError::NoCertificate);
        }

        Ok(SigningKey {
            private_key_der,
            cert_chain,
        })
    }

    /// Decrypt a PBES2-encrypted blob using the algorithm identified in
    /// `params_der` (DER-encoded `AlgorithmIdentifier` parameters) and the
    /// given password.  Returns the plaintext as a new `Vec<u8>`.
    fn pbes2_decrypt(
        params_der: &[u8],
        password: &str,
        ciphertext: &[u8],
    ) -> Result<Vec<u8>, String> {
        use der::Decode;
        use pkcs5::EncryptionScheme;
        use pkcs8::pkcs5::pbes2;

        let params = pbes2::Parameters::from_der(params_der)
            .map_err(|e| format!("PBES2 params parse: {e}"))?;
        let scheme = EncryptionScheme::from(params);
        let mut ct = ciphertext.to_vec();
        let pt = scheme
            .decrypt_in_place(password, &mut ct)
            .map_err(|e| format!("decrypt_in_place: {e}"))?;
        Ok(pt.to_vec())
    }

    fn decrypt_pkcs12_encryption(
        algorithm_der: &[u8],
        params_der: &[u8],
        password: &str,
        ciphertext: &[u8],
    ) -> Result<Vec<u8>, String> {
        if let Ok(plaintext) = Self::pbes2_decrypt(params_der, password, ciphertext) {
            return Ok(plaintext);
        }
        let algorithm = yasna::parse_der(algorithm_der, p12::AlgorithmIdentifier::parse)
            .map_err(|error| format!("legacy PBE algorithm parse: {error:?}"))?;
        let mut bmp_password = Vec::with_capacity(password.len() * 2 + 2);
        for codepoint in password.encode_utf16() {
            bmp_password.extend_from_slice(&codepoint.to_be_bytes());
        }
        bmp_password.extend_from_slice(&[0, 0]);
        algorithm
            .decrypt_pbe(ciphertext, &bmp_password)
            .ok_or_else(|| "legacy PKCS#12 PBE decrypt failed".to_owned())
    }

    fn decrypt_shrouded_key(bag_value: &[u8], key_password: &str) -> Result<Vec<u8>, SignError> {
        use der::asn1::AnyRef;
        use der::Decode;
        use pkcs8::EncryptedPrivateKeyInfo;

        let wrapper = AnyRef::from_der(bag_value).map_err(|error| {
            SignError::KeystoreParseError(format!("shrouded key wrapper: {error}"))
        })?;
        let encrypted_private_key = wrapper.value();

        if let Ok(encrypted) = EncryptedPrivateKeyInfo::from_der(encrypted_private_key) {
            let mut ciphertext = encrypted.encrypted_data.to_vec();
            if let Ok(private_key) = encrypted
                .encryption_algorithm
                .decrypt_in_place(key_password, &mut ciphertext)
            {
                return Ok(private_key.to_vec());
            }
        }

        let encrypted =
            yasna::parse_der(encrypted_private_key, p12::EncryptedPrivateKeyInfo::parse).map_err(
                |error| {
                    SignError::KeystoreParseError(format!("legacy shrouded key parse: {error:?}"))
                },
            )?;
        let mut password = Vec::with_capacity(key_password.len() * 2 + 2);
        for codepoint in key_password.encode_utf16() {
            password.extend_from_slice(&codepoint.to_be_bytes());
        }
        password.extend_from_slice(&[0, 0]);
        encrypted.decrypt(&password).ok_or_else(|| {
            SignError::KeystoreParseError(
                "shrouded key decryption failed for PBES2 and PKCS#12 PBE".to_owned(),
            )
        })
    }

    // -----------------------------------------------------------------------
    // Legacy path: 3DES / RC2 (via the `p12` crate)
    // -----------------------------------------------------------------------

    fn from_pkcs12_legacy(
        p12_bytes: &[u8],
        store_password: &str,
        key_alias: &str,
        key_password: &str,
    ) -> Result<Self, SignError> {
        use p12::PFX;

        let pfx = PFX::parse(p12_bytes)
            .map_err(|e| SignError::KeystoreParseError(format!("legacy PKCS#12 parse: {e:?}")))?;

        let mut password = Vec::with_capacity(key_password.len() * 2 + 2);
        for codepoint in key_password.encode_utf16() {
            password.extend_from_slice(&codepoint.to_be_bytes());
        }
        password.extend_from_slice(&[0, 0]);
        let keys = pfx
            .bags(store_password)
            .map_err(|e| SignError::KeystoreParseError(format!("safe bags: {e:?}")))?
            .into_iter()
            .filter_map(|bag| {
                let alias = bag.friendly_name();
                bag.bag.get_key(&password).map(|key| (alias, key))
            })
            .collect();
        let private_key_der = Self::select_private_key(keys, key_alias)?;

        let certs = pfx
            .cert_x509_bags(store_password)
            .map_err(|e| SignError::KeystoreParseError(format!("cert bags: {e:?}")))?;
        if certs.is_empty() {
            return Err(SignError::NoCertificate);
        }

        Ok(SigningKey {
            private_key_der,
            cert_chain: certs,
        })
    }

    fn modern_friendly_name(bag: &pkcs12::safe_bag::SafeBag) -> Result<Option<String>, SignError> {
        use const_oid::ObjectIdentifier;
        use der::asn1::BmpString;

        const FRIENDLY_NAME: ObjectIdentifier =
            ObjectIdentifier::new_unwrap("1.2.840.113549.1.9.20");
        let Some(attributes) = bag.bag_attributes.as_ref() else {
            return Ok(None);
        };
        let Some(attribute) = attributes
            .iter()
            .find(|attribute| attribute.oid == FRIENDLY_NAME)
        else {
            return Ok(None);
        };
        let value = attribute.values.get(0).ok_or_else(|| {
            SignError::KeystoreParseError("empty PKCS#12 friendlyName attribute".into())
        })?;
        value
            .decode_as::<BmpString>()
            .map(|name| Some(name.to_string()))
            .map_err(|error| {
                SignError::KeystoreParseError(format!("PKCS#12 friendlyName decode: {error}"))
            })
    }

    fn select_private_key(
        keys: Vec<(Option<String>, Vec<u8>)>,
        key_alias: &str,
    ) -> Result<Vec<u8>, SignError> {
        if keys.is_empty() {
            return Err(SignError::NoPrivateKey);
        }
        let available = keys
            .iter()
            .enumerate()
            .map(|(index, (alias, _))| alias.clone().unwrap_or_else(|| (index + 1).to_string()))
            .collect::<Vec<_>>();
        keys.into_iter()
            .enumerate()
            .find_map(|(index, (alias, key))| {
                let alias = alias.unwrap_or_else(|| (index + 1).to_string());
                (alias == key_alias).then_some(key)
            })
            .ok_or_else(|| SignError::KeyAliasNotFound {
                alias: key_alias.to_owned(),
                available,
            })
    }

    // -----------------------------------------------------------------------
    // PEM path
    // -----------------------------------------------------------------------

    /// Load from a separate PEM private key + PEM certificate.
    ///
    /// The PEM private key must be PKCS#8 (`BEGIN PRIVATE KEY`) format.
    /// The PEM certificate must be X.509 (`BEGIN CERTIFICATE`) format.
    pub fn from_pem(private_key_pem: &str, cert_pem: &str) -> Result<Self, SignError> {
        let private_key_der = Self::pkcs8_der_from_pem(private_key_pem)?;
        let cert_der = Self::cert_der_from_pem(cert_pem)?;

        Ok(SigningKey {
            private_key_der,
            cert_chain: vec![cert_der],
        })
    }

    /// Extract PKCS#8 DER bytes from a PEM-encoded private key string.
    fn pkcs8_der_from_pem(pem: &str) -> Result<Vec<u8>, SignError> {
        let pem = pem.trim();
        let b64 = pem
            .lines()
            .filter(|l| !l.starts_with("-----"))
            .collect::<Vec<_>>()
            .join("");
        base64_decode(&b64).map_err(|e| SignError::PemError(format!("base64 decode: {e}")))
    }

    /// Extract DER bytes from a PEM-encoded certificate string.
    fn cert_der_from_pem(pem: &str) -> Result<Vec<u8>, SignError> {
        let pem = pem.trim();
        let b64 = pem
            .lines()
            .filter(|l| !l.starts_with("-----"))
            .collect::<Vec<_>>()
            .join("");
        base64_decode(&b64).map_err(|e| SignError::PemError(format!("base64 decode: {e}")))
    }
}

/// Minimal base64 decoder (standard alphabet).
fn base64_decode(input: &str) -> Result<Vec<u8>, String> {
    const TABLE: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

    let mut lookup = [0xFFu8; 256];
    for (i, &c) in TABLE.iter().enumerate() {
        lookup[c as usize] = i as u8;
    }

    let bytes: Vec<u8> = input
        .bytes()
        .filter(|&b| b != b'\n' && b != b'\r' && b != b' ')
        .collect();

    let mut output = Vec::with_capacity((bytes.len() * 3) / 4);
    let mut i = 0;
    while i < bytes.len() {
        let b0 = bytes.get(i).copied().unwrap_or(b'=');
        let b1 = bytes.get(i + 1).copied().unwrap_or(b'=');
        let b2 = bytes.get(i + 2).copied().unwrap_or(b'=');
        let b3 = bytes.get(i + 3).copied().unwrap_or(b'=');

        let v0 = if b0 == b'=' { 0u8 } else { lookup[b0 as usize] };
        let v1 = if b1 == b'=' { 0u8 } else { lookup[b1 as usize] };
        let v2 = if b2 == b'=' { 0u8 } else { lookup[b2 as usize] };
        let v3 = if b3 == b'=' { 0u8 } else { lookup[b3 as usize] };

        if v0 == 0xFF || v1 == 0xFF {
            return Err(format!("invalid base64 char at position {i}"));
        }

        output.push((v0 << 2) | (v1 >> 4));
        if b2 != b'=' {
            if v2 == 0xFF {
                return Err(format!("invalid base64 char at position {}", i + 2));
            }
            output.push((v1 << 4) | (v2 >> 2));
        }
        if b3 != b'=' {
            if v3 == 0xFF {
                return Err(format!("invalid base64 char at position {}", i + 3));
            }
            output.push((v2 << 6) | v3);
        }
        i += 4;
    }
    Ok(output)
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    // ── Error cases ─────────────────────────────────────────────────────────

    #[test]
    fn test_empty_bytes_returns_err() {
        let result = SigningKey::from_pkcs12(&[], "", "key", "password");
        assert!(result.is_err(), "empty bytes must return Err, not panic");
    }

    #[test]
    fn test_random_bytes_returns_err() {
        let junk = b"this is definitely not a valid PKCS#12 file!";
        let result = SigningKey::from_pkcs12(junk, "pass", "key", "pass");
        assert!(result.is_err(), "random bytes must return Err");
    }

    #[test]
    fn test_wrong_password_returns_err() {
        let p12_path =
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/test.p12");
        if !p12_path.exists() {
            tracing::error!("SKIP: test P12 fixture not found at {:?}", p12_path);
            return;
        }
        let p12_bytes = std::fs::read(&p12_path).expect("read test.p12");
        let result = SigningKey::from_pkcs12(&p12_bytes, "wrong", "key", "wrong_password");
        assert!(result.is_err(), "wrong password must return Err");
    }

    /// Load the generated test PKCS#12 fixture (password: `test123`).
    ///
    /// This test requires the fixture file at
    /// `crates/arkdown-sign/tests/fixtures/test.p12`, generated by:
    /// ```bash
    /// openssl req -x509 -newkey rsa:2048 -keyout /tmp/key.pem -out /tmp/cert.pem \
    ///     -days 3650 -nodes -subj '/CN=test'
    /// openssl pkcs12 -export -out crates/arkdown-sign/tests/fixtures/test.p12 \
    ///     -inkey /tmp/key.pem -in /tmp/cert.pem -passout pass:test123
    /// ```
    #[test]
    fn test_load_rsa_p12_fixture() {
        let p12_path =
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/test.p12");
        if !p12_path.exists() {
            tracing::error!("SKIP: test P12 fixture not found at {:?}", p12_path);
            return;
        }
        let p12_bytes = std::fs::read(&p12_path).expect("read test.p12");
        let result = SigningKey::from_pkcs12(&p12_bytes, "test123", "1", "test123");
        assert!(
            result.is_ok(),
            "loading valid RSA P12 with correct password must succeed: {:?}",
            result.err()
        );
        let key = result.unwrap();
        assert!(
            !key.private_key_der.is_empty(),
            "private key DER must not be empty"
        );
        assert!(
            !key.cert_chain.is_empty(),
            "certificate chain must not be empty"
        );
        assert!(
            !key.cert_chain[0].is_empty(),
            "leaf certificate DER must not be empty"
        );
    }

    #[test]
    fn test_cert_chain_from_pem_file_uses_app_cert_file_contents() {
        use base64::Engine;

        let p12_path =
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/test.p12");
        if !p12_path.exists() {
            tracing::error!("SKIP: test P12 fixture not found at {:?}", p12_path);
            return;
        }
        let p12_bytes = std::fs::read(&p12_path).expect("read test.p12");
        let key = SigningKey::from_pkcs12(&p12_bytes, "test123", "1", "test123")
            .expect("load fixture p12");
        let cert = key.cert_chain.first().expect("fixture cert");
        let pem = format!(
            "-----BEGIN CERTIFICATE-----\n{}\n-----END CERTIFICATE-----\n",
            base64::engine::general_purpose::STANDARD.encode(cert)
        );
        let temp_dir = tempfile::tempdir().expect("tempdir");
        let cert_path = temp_dir.path().join("app.cer");
        std::fs::write(&cert_path, pem).expect("write app cert");

        let cert_chain =
            SigningKey::cert_chain_from_file(&cert_path).expect("read appCertFile cert chain");

        assert_eq!(cert_chain, vec![cert.clone()]);
    }

    /// Load a DevEco Studio-generated PKCS#12 (PBES2+PBKDF2+AES-256-CBC).
    ///
    /// Skipped when the fixture path does not exist on disk so CI is not broken.
    #[test]
    #[ignore = "requires caller-provided DevEco signing materials"]
    fn test_load_deveco_pbes2_p12() {
        let Some(p12_path) = std::env::var_os("HAPSIGNER_TEST_DEVECO_P12") else {
            return;
        };
        let Ok(password) = std::env::var("HAPSIGNER_TEST_DEVECO_P12_PASSWORD") else {
            return;
        };
        let alias = std::env::var("HAPSIGNER_TEST_DEVECO_P12_ALIAS")
            .unwrap_or_else(|_| "debugKey".to_string());
        let p12_bytes = std::fs::read(p12_path).unwrap();
        let key = SigningKey::from_pkcs12(&p12_bytes, &password, &alias, &password)
            .expect("should load PBES2 p12");
        assert!(!key.private_key_der.is_empty());
        assert!(!key.cert_chain.is_empty());
    }

    // ── from_pem: base64 decoder ─────────────────────────────────────────────

    /// Test that `from_pem` with invalid base64 returns Err without panicking.
    #[test]
    fn test_from_pem_invalid_base64_returns_err() {
        let bad_key = "-----BEGIN PRIVATE KEY-----\n!!!not base64!!!\n-----END PRIVATE KEY-----";
        let bad_cert = "-----BEGIN CERTIFICATE-----\n!!!not base64!!!\n-----END CERTIFICATE-----";
        let result = SigningKey::from_pem(bad_key, bad_cert);
        assert!(result.is_err(), "invalid PEM base64 must return Err");
    }

    /// Test that empty PEM blocks return Err (no DER bytes to parse).
    #[test]
    fn test_from_pem_empty_content_returns_err_or_ok_with_empty_key() {
        let empty_key = "-----BEGIN PRIVATE KEY-----\n-----END PRIVATE KEY-----";
        let empty_cert = "-----BEGIN CERTIFICATE-----\n-----END CERTIFICATE-----";
        // Empty PEM may produce Ok or Err — no panic is the requirement.
        let result = SigningKey::from_pem(empty_key, empty_cert);
        let _ = result;
    }

    /// Verify the base64 decoder handles padding correctly.
    #[test]
    fn test_base64_decode_known_vector() {
        let encoded = "aGVsbG8=";
        let pem = format!("-----BEGIN PRIVATE KEY-----\n{encoded}\n-----END PRIVATE KEY-----");
        let cert_pem = "-----BEGIN CERTIFICATE-----\naGVsbG8=\n-----END CERTIFICATE-----";
        let result = SigningKey::from_pem(&pem, cert_pem);
        // Result will be Err(PemError) because "hello" is not valid PKCS#8,
        // but the error must NOT be from base64 decode.
        if let Err(crate::error::SignError::PemError(msg)) = &result {
            assert!(
                !msg.contains("base64 decode"),
                "base64 decode of 'aGVsbG8=' must succeed; got PemError: {msg}"
            );
        }
    }
}
